### ISSUE TITLE
Add content on how to use safe ways of inputting user data to C programs

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#363] opened 2018-10-17 09:28 UTC
As disappointing as being told to take 'other C courses' to be able to use safe ways of inputting user data to C programs!! Why wasn't this brought up in any of the preceding 5 courses in this series?

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/632a112f8d4e46c88cf195f34e486a4f/7c1d9bb1804444f092456eeeecb8cffd/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4064bda04351f749b8b15051f67feefd29

**Comment by remisharrock** [comment] 2018-10-17 12:55
duplicate of #356

**Closed as completed** 2018-10-17 16:41 UTC
Labels: duplicate, content improvement
