### ISSUE TITLE
Video  Codecast

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#236] opened 2018-10-01 17:38 UTC
Which course: 1 Getting Started What type of content: Video  Codecast URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/09151bec3f5c43f2b56e181e2ad87d03/?child=first Description: It was a very good idea to ad subtitles in English but I can't make it work proprly  actually there's subtitles but they don't match with the course. other comments:  your name: Fanny screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? Safari 12.0 Status actuel:

**Comment by EllaHa** [comment] 2018-10-02 06:12
Not able to reproduce this bug.

**Comment by Kitkatniss** [comment] 2018-10-02 16:43
All texts from Mooc 1 and Mooc2 have been reviewed.

Have they been put back in rights places  ?

**Comment by Kitkatniss** [comment] 2018-10-03 16:14
#30

**Comment by Kitkatniss** [comment] 2018-10-05 00:41
#31 
close this report, thx

**Comment by mgoudz** [comment] 2018-10-08 18:51
Now working properly

**Closed as completed by mgoudz** 2018-10-08 18:51 UTC
Labels: question, subtitles
