### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#107] opened 2018-10-01 17:26 UTC
Which course: 3 Modular Programming and Memory Management What type of content: Video URL: https://docs.google.com/forms/d/e/1FAIpQLSepiYJTpT-6qEJ1RyLbHOYOT39MzVw1fKl-5MDIp55VVfA4Kw/formResponse Description: No subtitles other comments:  your name: Isa screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by petraBT** [comment] 2018-10-02 21:02
Link does not work. Most likely duplicate of #106.

**Closed as completed by petraBT** 2018-10-02 21:02 UTC
Labels: question
