### ISSUE TITLE
Taskgrader

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#254] opened 2018-10-01 17:38 UTC
Which course: 3 Modular Programming and Memory Management What type of content: Taskgrader URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/?child=first Description: The solution given is not related to the exercise. other comments:  your name:  screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? firefox Status actuel: To do Chris

**Comment by chrissmiller** [comment] 2018-10-02 01:06
Unable to reproduce

**Comment by remisharrock** [comment] 2018-10-02 09:25
@chrissmiller 

I can't find the code in cloud9 for 

 4a_T Activity: compute space for tracking codes 

I only found the title in the pedagogical scenario in unit 3.2

https://docs.google.com/document/d/1hJJq3lEEpOqMDOqAlRbUpTmIi2crNL1QKLEWuRvIdcE/edit# 

is it related ?

**Comment by remisharrock** [comment] 2018-10-02 09:56
Anyways it looks it's not this activity: 
Activity: compute space for tracking codes
maybe this one ? Activity: programming a toaster (memory usage nicely displayed)

**Comment by remisharrock** [comment] 2018-10-02 10:05
@chrissmiller  @EllaHa  what is the difference between Dartmouth/C103/Week2/MemorySpaceHumanized  and  Dartmouth/C103/Week2/memorySpaceHumanized  ?  Uppercase M or lowercase m ? Is the one with a lowercase used somewhere ?

**Comment by petraBT** [comment] 2018-10-02 10:25
This was the toaster activity - the link to edX doesn't specify which particular part of a unit you get to. Toaster activity is fixed now - indeed had an issue (this is MemorySpaceHumanized).

**Closed as completed by petraBT** 2018-10-02 10:25 UTC
Labels: question
